spin/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import javascript_catalog
from spin import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'spin.views.home', name='home'),
    # url(r'^spin/', include('spin.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += i18n_patterns('',
	url(r'^', include('spin_base.urls', namespace='spin')),
)

urlpatterns += patterns('',
    (r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spin_base/urls.py
# This Python file uses the following encoding: utf-8

from django.conf.urls import patterns, include, url
from spin_base.views import HomeView, UserHomeView, UserDetail, FollowersList, FollowingList, PublicProfiles
from spin_base.views import RegistrationView, LoginView, LogoutView, AccountView, AccountDelete, ActivationView
from spin_base.views import Follow, StopFollow, AddBlock, RemoveBlock, ApproveFollowing
from spin_base.views import CreateSpin, PublicSpin, CommentSpin, EditSpin, DeleteSpin, DetailSpin, DeleteComment
from spin_base.views import ReSpinView, Search
from spin_base.views import ReportCommentView, ReportSpinView, ReportUserView
from spin_base.views import CustomizationView, RestoreCustomization
from spin_base.views import PasswordRecovery, UsernameRecovery, SetNewPassword
from django.views.generic import TemplateView

# general urls
urlpatterns = patterns('',
		url('^$', HomeView.as_view(), name='home'),
		url('^home/(\?page=(?P<page>[0-9]+))?$', UserHomeView.as_view(), name='user-home'),
		url('^(?P<slug>\w+)/profile/(\?page=(?P<page>[0-9]+))?$', UserDetail.as_view(), name='user-profile'),
		url('^(?P<username>\w+)/following/(\?page=(?P<page>[0-9]+))?$', FollowingList.as_view(), name="user-following-list"),
		url('^(?P<username>\w+)/followers/(\?page=(?P<page>[0-9]+))?$', FollowersList.as_view(), name='user-followers-list'),
		url('^public/profiles/(\?page=(?P<page>[0-9]+))?$', PublicProfiles.as_view(), name='public-profiles'),
		url('^public/spins/(\?page=(?P<page>[0-9]+))?$', PublicSpin.as_view(), name='latest-spins'),
		url('^search/$', Search.as_view(), name="search")
	)

# accounting urls
urlpatterns += patterns('',
		url('^user/logout/$', LogoutView.as_view(), name='logout'),
		url('^congratulation/$', TemplateView.as_view(
			template_name="spin_base/accounting/registration_successfull.html"), name='registration_complete'),
		url('^registration/$', RegistrationView.as_view(), name='registration'),
		url('^login/$', LoginView.as_view(), name='login'),
		url('^account/$', AccountView.as_view(), name="user-account" ),
		url('^delete/$', AccountDelete.as_view(), name="delete-account"),
		url('^activation/(?P<pk>\d+)/a/(?P<activation_key>[\w:-_]+)', ActivationView.as_view(), name="activation"),
		url('^user/recovery/$', UsernameRecovery.as_view(), name='username-recovery' ),
		url('^password/recovery/$', PasswordRecovery.as_view(), name='password-recovery' ),
		url('^(?P<pk>\d+)/passrecovery/$', SetNewPassword.as_view(), name='set-new-password' ),
	)

# following urls
urlpatterns += patterns('',
		url('^(?P<username>\w+)/follow/$', Follow.as_view(), name='user-follow'),
		url('^(?P<username>\w+)/stopfollow/$', StopFollow.as_view(), name='user-stop-follow'),
		url('^(?P<username>\w+)/block/$', AddBlock.as_view(), name='user-block'),
		url('^(?P<username>\w+)/removeblock/$', RemoveBlock.as_view(), name='user-remove-block'),
		url('^(?P<username>\w+)/(?P<method>(accept|reject){1})/$', ApproveFollowing.as_view(), name='user-approve'),
	)

# spins urls
urlpatterns += patterns('',
		url('^spin-it/$', CreateSpin.as_view(), name="create-spin"),
		url('^spin/edit/(?P<pk>\d+)/$', EditSpin.as_view(), name="edit-spin"),
		url('^(?P<spin_id>\d+)/delete/$', DeleteSpin.as_view(), name="delete-spin"),
		url('^(?P<spin_id>\d+)/comment/$', CommentSpin.as_view(), name='comment-spin' ),
		url('^(?P<spin_id>\d+)/respin/$', ReSpinView.as_view(), name='respin'),
		url('^(?P<pk>\d+)/details/$', DetailSpin.as_view(), name='spin'),
		url('^(?P<pk>\d+)/delete/comment/$', DeleteComment.as_view(), name='delete-comment'),
	)

# reporting urls
urlpatterns += patterns('',
	url('^report/comment/(?P<comment>\d+)$', ReportCommentView.as_view(), name='report-comment'),
	url('^report/spin/(?P<spin>\d+)$', ReportSpinView.as_view(), name='report-spin'),
	url('^report/user/(?P<userid>\d+)$', ReportUserView.as_view(), name='report-user'),
	)

# customizations urls
urlpatterns += patterns('',
	url('^customize/$', CustomizationView.as_view(), name='customize' ),
	url('^reset/customization/$', RestoreCustomization.as_view(), name='restore-customization' )
	)

spin_base/views/customization.py
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from spin_base.models import Customization
from spin_base.forms import CustomizeForm, SpinForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


class CreateCustomizationView(CreateView):
	'''
	This view creates a customization look for the app.
	'''
	model = Customization
	form_class = CustomizeForm
	template_name = 'spin_base/generic/customize.html'
	context_object_name = 'custom'

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(CreateCustomizationView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(CreateCustomizationView, self).get_context_data(**kwargs)
		context['spin_form'] = SpinForm()
		return context

	def get_success_url(self):
		return self.request.session.get('path')

	def form_valid(self, form):
		customization = form.save(commit=False)
		user = self.request.user.userprofile
		previous_style = user.style
		if previous_style is not None and previous_style.style_users.count() == 1:
			previous_style.delete()
		ret = super(CreateCustomizationView, self).form_valid(form)
		user.style=customization
		user.save()
		return ret


class UpdateCustomizationView(UpdateView):
	'''
	This view updates the user customized look for the app.
	'''
	model = Customization
	form_class = CustomizeForm
	template_name = 'spin_base/generic/customize.html'

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(UpdateCustomizationView, self).dispatch(request, *args, **kwargs)
	
	def get_context_data(self, **kwargs):
		context = super(UpdateCustomizationView, self).get_context_data(**kwargs)
		context['spin_form'] = SpinForm()
		return context

	def get_success_url(self):
		return self.request.session.get('path')


class CustomizationView(View):
	'''
	This view dispatches the requests for update and create.
	It look for a present customization, if not present, calls CreateCustomizationView, else UpdateCustomizationView.
	'''
	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		style = request.user.userprofile.style
		if not style:
			view = CreateCustomizationView.as_view()
		else:
			view = UpdateCustomizationView.as_view()
			kwargs['pk'] = style.id
		return view(request, *args, **kwargs)

class RestoreCustomization(View):
	'''
	Resets the app look.
	'''
	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		style = request.user.userprofile.style
		style.nav_inverse=True
		style.well_color=''
		style.background_color=''
		style.background_image=''
		style.save()
		return HttpResponseRedirect(reverse('spin:customize'))

spin_base/views/generic.py
# This Python file uses the following encoding: utf-8

from django.views.generic import TemplateView, ListView
from django.utils.translation import ugettext as _
from spin_base.forms import LoginForm, RegistrationForm, SpinForm, CommentForm
from spin_base.models import UserProfile, Spin
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404


class HomeView(TemplateView):
	'''
	This view displays home page. If user is authenticated this redirects to
	following and followers' ribbits page, else this shows the home page with
	login form and registration one.
	'''

	template_name = 'spin_base/home_base.html'
	'''
	Class attribute which defines the page to display in response to a user call.
	'''

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated() and request.user.is_active:
			return HttpResponseRedirect( reverse('spin:user-home') )
		return super(HomeView, self).dispatch(request, *args, **kwargs)


	def get_context_data(self, **kwargs):
		context = {}
		username = self.request.get_signed_cookie('access', False)
		if username:
			login_form = LoginForm(initial={'username': username, 'remember': True})
		else:
			login_form = LoginForm()
		context['login_form'] = login_form
		context['registration_form'] = RegistrationForm()
		return context


class UserHomeView(ListView):
	'''
	This view displays the home for authenticated users.
	The home shows the list of latest followers' spins.
	'''
	# queryset = Spin.objects.all()
	paginate_by = 15
	template_name = 'spin_base/user_home.html'
	context_object_name = 'relevant_elements'

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(UserHomeView, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		try:
			kwargs['page']
		except:
			kwargs['page']=1
		context = super(UserHomeView, self).get_context_data(**kwargs)
		self.request.session['path'] = self.request.path
		context['comment_form'] = CommentForm()
		context['spin_form'] = SpinForm()
		context['home_active'] = 'active'
		return context

	def get_queryset(self):
		return Spin.objects.filter(author__user_followed__follower=self.request.user.userprofile, author__user_followed__approved=True)


class PublicProfiles(ListView):
	'''
	This view displays the public user profiles, so the user can start following someone.
	'''
	#queryset = UserProfile.objects.all().filter(private=False).order_by('-spinned__date').distinct('username')
	template_name = 'spin_base/generic/user_list.html'
	context_object_name = 'user_list'
	paginate_by = 15

	def get_context_data(self, **kwargs):
		context = super(PublicProfiles, self).get_context_data(**kwargs)
		self.request.session['path'] = self.request.path
		context['list_title'] = _('Public profiles on Spin:')
		context['spin_form'] = SpinForm()
		context['public_profiles_active'] = 'active'
		return context

	def get_queryset(self):
		return UserProfile.objects.filter(private=False).exclude(username=self.request.user.username).order_by('last_login')

class ListControl(ListView):
	'''
	Utility class that defines the base list actions for followers and followings lists.
	'''
	template_name = 'spin_base/generic/user_list.html'
	context_object_name = 'user_list'

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		if request.user.username != kwargs['username']:
			try:
				target_user = UserProfile.objects.get(username=kwargs['username'])
			except:
				pass
			else:
				if (target_user.private and target_user.user_followed.filter(follower=request.user.userprofile, approved=True).exists())\
						or (not target_user.private):
					return super(ListControl, self).dispatch(request, *args, **kwargs)
			
			return HttpResponseRedirect(request.session.get('path', ''))
		else:
			return super(ListControl, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(ListControl, self).get_context_data(**kwargs)
		self.request.session['path'] = self.request.path
		context['spin_form'] = SpinForm()
		return context

class FollowersList(ListControl):
	'''
	Displays user's followers.
	'''
	# template_name = 'spin_base/user_list.html'
	# context_object_name = 'user_list'

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(FollowersList, self).dispatch(request, *args, **kwargs)

	def get_queryset(self):
		return UserProfile.objects.filter(user_following__followed__username=self.kwargs['username'],  user_following__approved=True)

	def get_context_data(self, **kwargs):
		context = {}
		context = super(FollowersList, self).get_context_data(**kwargs)
		context['active_followers'] = 'active'
		context['list_title'] = self.kwargs['username'] + " " + _('followers list')
		return context

class FollowingList(ListControl):
	'''
	Displays user's followings.
	'''
	# template_name = 'spin_base/user_list.html'
	# context_object_name = 'user_list'

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(FollowingList, self).dispatch(request, *args, **kwargs)

	def get_queryset(self):
		return UserProfile.objects.filter(user_followed__follower__username=self.kwargs['username'],  user_followed__approved=True)

	def get_context_data(self, **kwargs):
		context = {}
		context = super(FollowingList, self).get_context_data(**kwargs)
		context['active_following'] = 'active'
		context['list_title'] = self.kwargs['username'] + " " + _('following list')
		return context

spin_base/views/relationship_control.py
# This Python file uses the following encoding: utf-8

from django.views.generic import View
from django.http import HttpResponseRedirect
from spin_base.models import UserProfile, Relationship
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse


class AddBlock(View):
	'''
	This class manages adding block to user profile.
	'''
	
	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		super(AddBlock, self).dispatch(request, *args, **kwargs)
		user_to_block = get_object_or_404(UserProfile, username=kwargs['username'])
		if user_to_block not in request.user.userprofile.blocked.all():
			request.user.userprofile.blocked.add(user_to_block)
			try:
				rel = request.user.userprofile.user_followed.get(follower=user_to_block)
			except:
				# the user is not followed by the blocked one
				pass
			else:
				rel.delete()
		return HttpResponseRedirect(request.session.get('path', ''))

class RemoveBlock(View):
	'''
	This class manages removing block to user profile.
	'''

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		super(RemoveBlock, self).dispatch(request, *args, **kwargs)
		user_blocked = get_object_or_404(UserProfile, username=kwargs['username'])
		if user_blocked in request.user.userprofile.blocked.all():
			request.user.userprofile.blocked.remove(user_blocked)

		return HttpResponseRedirect(request.session.get('path', ''))

class Follow(View):
	'''
	This class permits user to follow another one or to ask following.
	'''

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		super(Follow, self).dispatch(request, *args, **kwargs)
		user_to_follow = get_object_or_404(UserProfile, username=kwargs['username'])
		if self.request.user.userprofile not in user_to_follow.blocked.all():
			if not user_to_follow.user_followed.filter(follower=request.user.userprofile).exists():
				rel = Relationship(follower=request.user.userprofile, followed=user_to_follow)
				if user_to_follow.private:
					rel.approved = False
				rel.save()

		return HttpResponseRedirect(request.session.get('path', ''))

class StopFollow(View):
	'''
	This class removes the following relationship from one side of this one.
	'''

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		super(StopFollow, self).dispatch(request, *args, **kwargs)
		user_followed = get_object_or_404(UserProfile, username=kwargs['username'])
		try:
			rel = user_followed.user_followed.get(follower=request.user.userprofile)
		except:
			# the user is not a follower
			pass
		else:
			rel.delete()

		return HttpResponseRedirect(request.session.get('path', ''))

class ApproveFollowing(View):
	'''
	This class permits private users to approve the following requests.
	If a user wants to disapprove, he should call StopFollow.
	'''

	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		super(ApproveFollowing, self).dispatch(request, *args, **kwargs)
		if self.request.user.userprofile.private:
			user_waiting = get_object_or_404(UserProfile, username=kwargs['username'])
			try:
				rel = request.user.userprofile.user_followed.get(follower=user_waiting, approved=False)
			except:
				# there is no waiting relation or it's approved
				pass
			else:
				if kwargs['method'] == 'accept':
					rel.approved=True
					rel.save()
				else:
					rel.delete()

		return HttpResponseRedirect(reverse('spin:user-profile', kwargs={'slug': self.request.user.username}))

spin_base/templates/forms/comment_form.html
{% load i18n %}

<div class="row-fluid comment-area">
	<div class="span* well">
		<formfield>
			<form method="post" class="comment-form" action="{% url 'spin:comment-spin' spin_id=spin.id %}">
				{% csrf_token %}
				<div class="control-group {% if comment_form.content.errors %}error{% endif %}">
					<div class="control">
						<div class="row-fluid">
							{{comment_form.content}}
							{% if comment_form.content.errors %}
								<span class="help-block">
									{% for error in comment_form.content.errors %}
										{{ error }}<br/>
									{% endfor %}
								</span>
							{% endif %}
						</div>
					</div>
				</div>
				<div class="span*">
					<input type="submit" class="btn" value="{% trans 'Comment' %}"/>
				</div>
			</form>
		</formfield>
	</div>
</div>

spin_base/templates/forms/inline_login.html
{% load i18n %}
<div>
	<form class="form-inline" method="POST" action="#">
		{% if login_form.non_field_errors %}
			<div class="control-group error">
				<span class="help-inline">{% trans 'Wrong username or password' %}</span>
			</div>
		{% endif %}
		{% csrf_token %}
		<div class="input-prepend">
			<span class="add-on">@</span>
			{{ login_form.username }}
		</div>
	    {{ login_form.password }}
	    <label class="checkbox">{% trans 'Remember me' %}
	    	{{ login_form.remember }}
	    </label>
		<input type="submit" class="btn" value="{% trans 'Sign in' %}" />
	</form>
</div>

spin_base/templates/forms/login.html
{% load i18n %}
{% block extrahead %}
	{{login_form.media}}
{% endblock %}

<form method="post" action="{% url 'spin:login' %}" class="spin-form">
	<fieldset>
		<legend>Login</legend>
		{% if login_form.non_field_errors %}
			<div class="control-group error">
				<span class="help-inline">{{login_form.non_field_errors}}</span>
			</div>
		{% endif %}
		{% csrf_token %}
		<div class="control-group span*">
			<label for="inputUsername">{% trans 'Username' %}</label>
			<div class="controls">
				{{ login_form.username }}
			</div>
		</div>
		<div class="control-group span*">
			<label for="inputPassword">Password</label>
			<div class="controls">
				{{ login_form.password }}
			</div>
		</div>
		<div class="control-group span*">
			<div class="controls">
				<label class="checkbox">
					{{ login_form.remember }}{% trans 'Remember me' %}
				</label>
				<input type="submit" class="btn" value="{% trans 'Sign in' %}"/>
			</div>
		</div>
	</fieldset>
	<div class="row-fluid">
		<a href="{% url 'spin:password-recovery' %}">{% trans 'Have you lost your data? Get them back' %}</a>
	</div>
</form>

spin_base/templates/forms/lost_password.html
{% extends 'spin_base/home_base.html' %}
{% load i18n %}

{% block extrahead %}
	{{form.media}}
{% endblock %}

{% block content %}
	<div class="span6 offset3 well">
		<form action="{% url 'spin:password-recovery' %}" class="spin-form" method="post">
			<fieldset>
				<legend>{% trans 'Recover your password' %}</legend>
				{% csrf_token %}
				<div class="control-group {% if form.username.errors %}error{% endif %}">
					<label>{% trans 'Please, insert your username' %}</label>
					<div class="control">
						{{form.username}}
						{% if form.username.errors %}
							<span class="help-block">
								{% for error in form.username.errors %}
									{{ error }}<br/>
								{% endfor %}
							</span>
						{% endif %}
					</div>
				</div>
				<input type="submit" value="{% trans 'Recover' %}" />
			</fieldset>
		</form>
		<div class="row-fluid">
			<a href="{% url 'spin:username-recovery' %}">{% trans 'Recover your username' %}</a>
		</div>
	</div>
{% endblock %}

spin_base/templates/forms/lost_username.html
{% extends 'spin_base/home_base.html' %}
{% load i18n %}

{% block extrahead %}
	{{form.media}}
{% endblock %}

{% block content %}
	<div class="span6 offset3 well">
		<form action="{% url 'spin:username-recovery' %}" class="spin-form" method="post">
			<fieldset>
				<legend>{% trans 'Recover your username' %}</legend>
				{% csrf_token %}
				<div class="control-group {% if form.email.errors %}error{% endif %}">
					<label>{% trans 'Please, insert your email address' %}</label>
					<div class="control">
						{{form.email}}
						{% if form.email.errors %}
							<span class="help-block">
								{% for error in form.email.errors %}
									{{ error }}<br/>
								{% endfor %}
							</span>
						{% endif %}
					</div>
				</div>
				<input type="submit" value="{% trans 'Recover' %}" />
			</fieldset>
		</form>
	</div>
{% endblock %}

spin_base/templates/forms/recovery_password.html
{% extends 'spin_base/home_base.html' %}
{% load i18n %}


{% block extrahead %}
	{{form.media}}
{% endblock %}

{% block content %}
	<div class="row-fluid well">
		<form action="{% url 'spin:set-new-password' pk=recovery.pk %}" class="spin-form" method="post">
			<fieldset>
				<legend>{% trans 'Recover your password' %}</legend>
				{% if form.non_field_errors %}
					<div class="alert alert-block alert-error fade in">
						<span class="alerthelp-inline">{{ form.non_field_errors }}</span>
					</div>
				{% endif %}
				{% csrf_token %}
				<div class="control-group {% if form.username.errors %}error{% endif %}">
					<label>{% trans 'Please, insert your username' %}</label>
					<div class="control {% if form.username.errors %}error{% endif %}">
						{% if form.username.errors %}
							<span class="help-block">
								{% for error in form.username.errors %}
									{{ error }}<br/>
								{% endfor %}
							</span>
						{% endif %}
						{{form.username}}
					</div>
				</div>
				<div class="control-group {% if form.password.errors %}error{% endif %}">
					<label>{% trans 'Insert a new password and confirm it' %}</label>
					<div class="control {% if form.password.errors %}error{% endif %}">
						{% if form.password.errors %}
							<span class="help-block">
								{% for error in form.password.errors %}
									{{ error }}<br/>
								{% endfor %}
							</span>
						{% endif %}
						{{form.password}}
						{{form.confirm_password}}
					</div>
				</div>
				<input type="submit" value="{% trans 'Set new' %}" />
			</fieldset>
		</form>
	</div>
{% endblock %}

spin_base/templates/forms/registration.html
{% load i18n %}
{% block extrahead %}
	{{registration_form.media}}
{% endblock %}

<form  method="post" action="{% url 'spin:registration' %}" class="spin-form" id="registration-form">
	<fieldset>
		<legend>{% trans "Registration" %}</legend>
		{% if registration_form.non_field_errors %}
			<div class="alert alert-block alert-error fade in">
				<span class="alerthelp-inline">{{ registration_form.non_field_errors }}</span>
			</div>
		{% endif %}
		{% csrf_token %}
		<div class="control-group 
			{% if registration_form.first_name.errors %}error{% endif %} 
			">
			<label for="inputName">{% trans 'First name' %}</label>
			<div class="controls">
				{% if registration_form.first_name.errors %}
					<span class="help-block">
						{% for error in registration_form.first_name.errors %}
							{{ error }}<br/>
						{% endfor %}
					</span>
				{% endif %}
				{{ registration_form.first_name }}
			</div>
		</div>
		<div class="control-group 
			{% if registration_form.last_name.errors %}error{% endif %}
			">
			<label for="inputSurname">{% trans 'Last name' %}</label>
			<div class="controls">
				{% if registration_form.last_name.errors %}
					<span class="help-block">
						{% for error in registration_form.last_name.errors %}
							{{ error }}<br/>
						{% endfor %}
					</span>
				{% endif %}
				{{ registration_form.last_name }}
			</div>
		</div>
		<div class="control-group 
			{% if registration_form.email.errors %}error{% endif %}
			">
			<label for="inputEmail">Email</label>
			<div class="controls">
				{% if registration_form.email.errors %}
					<span class="help-block">
						{% for error in registration_form.email.errors %}
							{{ error }}<br/>
						{% endfor %}
					</span>
				{% endif %}
				{{ registration_form.email }}
			</div>
		</div>
		<div class="control-group
			{% if registration_form.username.errors %}error{% endif %}
			">
			<label for="inputUsername">{% trans 'Username' %}</label>
			<div class="controls">
				{% if registration_form.username.errors %}
					<span class="help-block">
						{% for error in registration_form.username.errors %}
							{{ error }}<br/>
						{% endfor %}
					</span>
				{% endif %}
				{{ registration_form.username }}
			</div>
		</div>
		<div class="control-group
			{% if registration_form.password.errors %}error{% endif %}
			">
			<label for="inputPassword">Password</label>
			<div class="controls">
				{% if registration_form.password1.errors %}
					<span class="help-block">
						{% for error in registration_form.password1.errors %}
							{{ error }}<br/>
						{% endfor %}
					</span>
				{% endif %}
				{{ registration_form.password1 }}
			</div>
		</div>
		<div class="control-group">
			<label for="inputPasswordConfirm">{% trans 'Confirm Password' %}</label>
			<div class="controls">
				{% if registration_form.password2.errors %}
					<span class="help-block">
						{% for error in registration_form.password2.errors %}
							{{ error }}<br/>
						{% endfor %}
					</span>
				{% endif %}
				{{ registration_form.password2 }}
			</div>
		</div>
		<div class="control-group">
			<label class="checkbox">{% trans 'Do you want a private profile?' %}
				{{ registration_form.private }}
			</label>
		</div>
		<div class="control-group">
			<input type="submit" class="btn span*" value="{% trans 'Register' %}" />
		</div>
	</fieldset>
</form>